### PR TITLE
Added functionality that looks for Roles that are assumable by AWS Principals

### PR DESCRIPTION
**Pull request by relotnek**
Copied some of the code from list_roles and isolated roles that are assumable by AWS Principals. When sub-accounts are managed by parent entities or when access is provided to an external account, it can be helpful to know in multi-account AWS deployments.

Many of these sub accounts will grant implicit access to an external account allowing any one with sts:assumerole permissions on all resources to leverage the role returned by the output.

This excludes roles that can be assumed by AWS services

### CODE REVIEW

**Comment by carnal0wnage** [comment]
Hey thanks for the PR. we will take a look.  It does show a branch conflict. we did some module re-arranging to get ready to add some GCP functionality. you may need to update your folder structure.

**Comment by cktricky** [comment]
Hey @relotnek thanks for the PR! I believe you might have an old code-base in which you are trying to merge these changes. Can you pull from master and then update this branch accordingly? 

Thanks again for submitting!

**Comment by relotnek** [comment]
you got it, should be set - sorry about that

**Comment by cktricky** [comment]
No worries! Just happy to have the additional code 😄 🙇

**Pull request merged**
