### PR TITLE
because sorting is better than not

### PR DESCRIPTION
**Pull request by nvisium-jonn-callahan**

### CODE REVIEW

**Comment by carnal0wnage** [comment]
@nvisium-jonn-callahan  search_recon_by_key does sort when it returns results. see:
https://github.com/carnal0wnage/weirdAAL/blob/master/libs/sql.py  line115

does this do anything different?

**Comment by nvisium-jonn-callahan** [comment]
Yep, sorts the output alphabetically. That query is sorting by date checked via a `ORDER BY datetime(checked_at)`. Because of this, I was getting output such as this:

```
ec2:DescribeVpcEndpointServices
ec2:DescribeVpcEndpoints
ec2:DescribeVpcPeeringConnections
ec2:DescribeVpcs
ec2:CreateVpc
ec2:DescribeVpnConnections
ec2:DescribeVpnGateways
ecr:DescribeRepositories
ecs:ListClusters
ecs:DescribeClusters
ecs:ListContainerInstances
ecs:ListTaskDefinitions
efs:DescribeFileSystems
```

This threw me for a loop as I was checking for create* perms and scrolled past the large block of describe* and missed it. You could modify the `order by` to sort by `service` then `sub_service`, but I wasn't sure where else that query was leveraged, so figured it'd easiest to just sort the result set, especially considering you're not going to have a more than a few hundred items.

**Comment by carnal0wnage** [comment]
if you run recon_all twice thus putting the same stuff in the db will your code still give you the desired output sorted by time?

**Comment by nvisium-jonn-callahan** [comment]
I'm not following -- this PR sorts the output alphabetically regardless of the row order in either the DB or the result set. If sorting by time intentional, that's fine, but seems fairly counterintuitive. If anything, I think it'd be more sensible to sort the output of `module_list_services_by_key()` alphabetically and `module_list_services_by_key_with_date()` chronologically imo.

**Comment by carnal0wnage** [comment]
cool. i'm gonna merge this, then change how the sort with date is done because i want it to post the most recent first

**Comment by carnal0wnage** [comment]
actually nevermind i can live with how it is. thanks for the diff!

**Pull request merged**
